version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wso2-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wso2
      POSTGRES_PASSWORD: wso2123
      POSTGRES_DB: wso2db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wso2-network

  wso2is:
    image: wso2/wso2is:7.0.0
    container_name: wso2is-local
    ports:
      - "9444:9444"
    command: ["sh", "-c", "/home/wso2carbon/docker-entrypoint.sh -DportOffset=1 -Dorg.wso2.IdentityRESTAPISecurity.disableBasicAuth=false"]
    environment:
      - JVM_MEM_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./libs/postgresql-42.7.3.jar:/home/wso2carbon/wso2is-7.0.0/repository/components/lib/postgresql-42.7.3.jar
      - ./config/is/deployment.toml:/home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
    restart: unless-stopped
    networks:
      - wso2-network

  wso2apim:
    image: wso2/wso2am:4.3.0
    container_name: wso2apim-local
    ports:
      - "9443:9443"
      - "8243:8243"
      - "8280:8280"
    environment:
      - JVM_MEM_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./libs/postgresql-42.7.3.jar:/home/wso2carbon/wso2am-4.3.0/repository/components/lib/postgresql-42.7.3.jar
      - ./config/apim/deployment.toml:/home/wso2carbon/wso2am-4.3.0/repository/conf/deployment.toml
    restart: unless-stopped
    networks:
      - wso2-network

networks:
  wso2-network:
    driver: bridge

volumes:
  postgres_data: